In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
print(a)

[1 2 3 4 5]


In [5]:
import time
import sys

In [7]:
b = range(1000)
print(sys.getsizeof(5)*len(b))

28000


In [12]:
c = np.arange(1000)
print(c.itemsize*len(c))

4000


In [13]:
size = 10000000

In [14]:
l1 = range(size)
l2  = range(size)
a1 = np.arange(size)
a2 = np.arange(size)

In [22]:
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print((time.time() - start)*1000)


1733.327865600586


In [20]:
start = time.time()
resultA = a1 +a2
print((time.time() - start)*1000 ) 

39.89410400390625


In [24]:
a = np.array([[1,2],[3,4],[5,6]])

In [25]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [27]:
a.ndim

2

In [28]:
a.itemsize

4

In [29]:
a.shape

(3, 2)

In [34]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [37]:
range(3)

range(0, 3)

In [38]:
np.arange(4)

array([0, 1, 2, 3])

In [40]:
np.char.capitalize("njsn")

array('Njsn', dtype='<U4')

In [41]:
np.char.title("hello how are u")

array('Hello How Are U', dtype='<U15')

In [42]:
np.char.upper("nndn")

array('NNDN', dtype='<U4')

In [45]:
np.char.lower("BNNGhvdj")

array('bnnghvdj', dtype='<U8')

In [46]:
np.char.split("njvnd nfkjwn nvwi")

array(list(['njvnd', 'nfkjwn', 'nvwi']), dtype=object)

In [47]:
np.char.join([':'],['ffdf','fd'])

array(['f:f:d:f', 'f:d'], dtype='<U7')

In [48]:
np.char.replace("he is not a good boy",'not','very')

array('he is very a good boy', dtype='<U21')